# Generated by Django 5.1.1 on 2024-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMusic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('music', models.FileField(blank=True, upload_to='songs/audio/')),
                ('description', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('love_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='topartist/profile/images/')),
                ('title', models.CharField(max_length=256)),
                ('facebook_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('number_of_songs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='topartist/songs/images/')),
                ('title', models.CharField(max_length=256)),
                ('songs', models.FileField(blank=True, upload_to='topartist/songs/')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerFriendlyCollectionsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='beginnerfriendly/images/')),
                ('number_of_songs', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerFriendlyCollectionSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='beginnerfriendly/images/')),
                ('songs', models.FileField(blank=True, upload_to='beginnerfriendly/songs/')),
                ('description', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('general_query', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('song_listing', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('playlist_name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoverNewSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='discover/images/')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('songs', models.FileField(blank=True, upload_to='discovernewsongs/songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewSong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('song_name', models.CharField(max_length=256)),
                ('artist_name', models.CharField(max_length=256)),
                ('youtube_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('spotify_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCollections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='searchcollectionslist/images/')),
                ('likes', models.IntegerField(default=0)),
                ('number_of_songs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCollectionsSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='searchcollections/images/')),
                ('description', models.CharField(max_length=256)),
                ('songs', models.FileField(blank=True, upload_to='searchcollections/songs/')),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalCollectionsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='seasonalcollections/list/images/')),
                ('number_of_songs', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalCollectionSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='seasonalcollection/images/')),
                ('songs', models.FileField(blank=True, upload_to='seasonalcollections/songs/')),
                ('description', models.CharField(max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopArtistList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='topartist/images/')),
                ('title', models.CharField(max_length=256)),
                ('number_of_songs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingSongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='trendingsongs/images/')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('songs', models.FileField(blank=True, upload_to='trending/songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
